system:
  name: CartPole
  x_min: [-1.5, -0.35, -1.0, -1.0]
  x_max: [ 1.5,  0.35,  1.0,  1.0]
  u_min: [-5.0]
  u_max: [ 5.0]
  params:
    m_c: 2.0
    m_p: 0.5
    l: 0.5
    gravity: 9.81

constraint:
  type: state_limits_sdf
  params:
    limits:
      0: [-1.2, 1.2]
      1: [-0.25, 0.25]
    alpha: 30.0

data:
  enabled: true
  sampling: random
  num_samples:  400000
  method: branch_and_bound
  method_params:
    n_restarts: 2
  # method: mppi
  B: 500
  K: 50
  dt: 0.05
  # method_params:
  #   sigma: 1.75
  #   lam: 0.0
  #   n_iter: 5

pde:
  sampling: random
  num_samples: 800000

model:
  layers:
    - [4, null]
    - [32, "sin"]
    - [64, "sin"]
    - [64, "sin"]
    - [64, "sin"]
    - [32, "sin"]
    - [1, ["softplus", {beta: 10.0}]]
  rescale_inputs: true

training:
  epochs: 10000
  lr: 0.001
  lr_milestones: [8000]
  lr_gamma: 0.1
  pde_weight_mode: fixed
  pde_weight: 0.05

validation:
  enabled: true
  T: 3.0
  dt: 0.002
  sampling: stratified
  num_per_stratum: 500000

output:
  checkpoint_every: 1000
  log_every: 20
