system:
  name: DynamicUnicycle
  x_min: [-4.0, -4.0, -3.14, -2.0, -1.0]
  x_max: [ 4.0,  4.0,  3.14,  2.0,  1.0]
  u_min: [-1.0, -1.0]
  u_max: [ 1.0,  1.0]
  params: {}

constraint:
  type: circle_sdf
  params:
    center: [0.0, 0.0]
    radius: 1.0

data:
  enabled: true
  sampling: random
  num_samples: 600000
  method: beam_search
  method_params: {}
  # method: mppi
  B: 1000
  K: 50
  dt: 0.1
  # method_params:
  #   sigma: [0.35, 0.35]
  #   lam: 0.0
  #   n_iter: 5

pde:
  sampling: random
  num_samples: 1000000

model:
  layers:
    - [5, null]
    - [64, "sin"]
    - [64, "sin"]
    - [64, "sin"]
    - [64, "sin"]
    - [1, ["softplus", {beta: 10.0}]]
  rescale_inputs: true

training:
  epochs: 10000
  lr: 0.001
  lr_milestones: [7000]
  lr_gamma: 0.1
  pde_weight_mode: fixed
  pde_weight: 0.6

validation:
  enabled: true
  T: 5.0
  dt: 0.01
  sampling: stratified
  num_per_stratum: 500000

output:
  checkpoint_every: 1000
  log_every: 20
