"""Train a VertexCBF value function from a YAML config.

Artifacts are auto-routed into a per-method group sub-folder so the three
paper conditions stay separated on disk:
    NO_DATA — PDE/HJB residual loss only (no supervision).  Triggered by
              ``data.enabled: false`` or the ``--no-data`` flag.
    FC_DATA — "full-control" data: sampling-based MPC over the full control
              set (``mppi``).
    VRC_DATA — "vertex-restricted control" data: tree search over the control
              vertices (``beam_search``, ``stochastic_beam_search``,
              ``branch_and_bound``).
Default paths become::
    checkpoints/<GROUP>/<system>/{final.pt, validation.{pt,json}, timing.json}
    data/precomputed/<GROUP>/<system>.pt

Usage
-----
    # Basic run — supervision data is (re)generated by default and the
    # result is saved to data.cache_path:
    python scripts/train.py --config configs/double_integrator_1d.yaml

    # Reuse cached supervision data if present (skips data generation):
    python scripts/train.py --config configs/double_integrator_1d.yaml --reuse-data

    # PDE loss only (no supervision data) → artifacts go under NO_DATA/:
    python scripts/train.py --config configs/double_integrator_1d.yaml --no-data

    # Resume from a checkpoint:
    python scripts/train.py --config configs/double_integrator_1d.yaml \\
        --resume checkpoints/VRC_DATA/double_integrator_1d/epoch_5000.pt

    # Validate only (uses <checkpoint_dir>/final.pt by default):
    python scripts/train.py --config configs/double_integrator_1d.yaml --validate-only

    # Validate only from a specific checkpoint:
    python scripts/train.py --config configs/double_integrator_1d.yaml \\
        --validate-only --resume checkpoints/VRC_DATA/double_integrator_1d/epoch_5000.pt

    # Override device:
    python scripts/train.py --config configs/double_integrator_1d.yaml --device cpu
"""

from __future__ import annotations

import argparse
import json
import os
import time

import torch
import yaml

from vertexcbf.config_utils import (
    build_constr_fn,
    build_dynamics,
    build_model,
    build_trajopt_runner,
    method_group,
)
from vertexcbf.trajopt._utils import _format_hms, progress_context
from vertexcbf.trainer import Trainer
from vertexcbf.validation import validate_cbf, stratified_sample_by_predicted_cbf


def _get_data(cfg: dict, dynamics, constr_fn, device: torch.device, reuse_data: bool):
    """Return (states, values, t_data) supervision tensors, or (None, None, None).

    t_data is the measured generation time in seconds, or None when data was
    loaded from cache (so the caller can recover the time from a previous run).

    By default the cache is regenerated. Pass ``reuse_data=True`` to load from
    ``data.cache_path`` when it exists.
    """
    data_cfg = cfg.get("data", {})
    if not data_cfg.get("enabled", True):
        return None, None, None

    group = method_group(data_cfg)
    cache_path = (
        data_cfg.get("cache_path")
        or f"data/precomputed/{group}/{dynamics.name}.pt"
    )
    if os.path.isfile(cache_path):
        if reuse_data:
            print(f"Loading precomputed data from: {cache_path}")
            saved = torch.load(cache_path, map_location=device, weights_only=True)
            return saved["states"].to(device), saved["values"].to(device), None
        os.remove(cache_path)
        print(f"Removed existing cache: {cache_path}")

    # Run the configured trajopt method and cache the result for future runs
    method = data_cfg.get("method", "beam_search")
    sampling = data_cfg.get("sampling", "grid")
    if sampling == "random":
        num_samples = data_cfg["num_samples"]
        print(
            f"Running {method} on {num_samples} random samples "
            f"(B={data_cfg['B']}, K={data_cfg['K']}, dt={data_cfg['dt']})..."
        )
        states = dynamics.get_uniform_state_samples(
            num_samples=num_samples, requires_grad=False
        )
    else:
        grid_shape = data_cfg["grid_shape"]
        print(
            f"Running {method} on grid {grid_shape} "
            f"(B={data_cfg['B']}, K={data_cfg['K']}, dt={data_cfg['dt']})..."
        )
        states = dynamics.get_uniform_state_grid(
            grid_shape=grid_shape, requires_grad=False
        ).reshape(-1, dynamics.nx)

    run_trajopt = build_trajopt_runner(data_cfg, dynamics, constr_fn)
    if device.type == "cuda":
        torch.cuda.synchronize(device)
    t_gen_start = time.time()
    with progress_context("Data generation"):
        values = run_trajopt(states)
    if device.type == "cuda":
        torch.cuda.synchronize(device)
    t_data = time.time() - t_gen_start
    print(f"Data generation complete in {_format_hms(t_data)}.")

    os.makedirs(os.path.dirname(os.path.abspath(cache_path)), exist_ok=True)
    torch.save({"states": states.cpu(), "values": values.cpu()}, cache_path)
    print(f"Data cached to: {cache_path}")

    return states, values, t_data


def _run_validation(
    cfg: dict, dynamics, constr_fn, model, default_dir: str, device: torch.device
) -> float | None:
    """Run closed-loop CBF validation, print per-stratum metrics, and save results.

    Two artifacts are written next to each other:

    * ``<output_path>``      — torch ``.pt`` with the initial states, per-state
      ``V(x_0)`` and ``min_k c(x_k)``, the stratified metrics, the metadata
      needed to reproduce the rollout, and (optionally) full state and
      control trajectories.  Suitable for plotting figures later.
    * ``<output_path>.json`` sidecar — JSON with the stratified metrics and
      metadata only.  Suitable for aggregating into result tables.
    """
    val_cfg = cfg.get("validation", {}) or {}
    if not val_cfg.get("enabled", False):
        return None

    T = val_cfg["T"]
    dt = val_cfg["dt"]
    sampling = val_cfg.get("sampling", "stratified")
    predicted_safe_prior: float | None = None
    if sampling == "stratified":
        num_per_stratum = int(val_cfg["num_per_stratum"])
        sample_info = stratified_sample_by_predicted_cbf(
            dynamics=dynamics,
            constr_fn=constr_fn,
            residual_fn=model,
            num_per_stratum=num_per_stratum,
            max_oversample=int(val_cfg.get("max_oversample", 100)),
        )
        states = sample_info["states"]
        # Unbiased estimate of Vol{V > 0}/Vol(state_box) used by validate_cbf
        # to reweight per-stratum rollout outcomes into volume ratios.
        attempts = int(sample_info["attempts"])
        total_ps = int(sample_info["total_predicted_safe"])
        predicted_safe_prior = (total_ps / attempts) if attempts > 0 else None
        empty_predicted_safe = bool(sample_info.get("empty_predicted_safe", False))
        sampling_meta = {
            "sampling": "stratified",
            "num_per_stratum": num_per_stratum,
            "n_predicted_safe": int(sample_info["n_predicted_safe"]),
            "n_predicted_unsafe": int(sample_info["n_predicted_unsafe"]),
            "sampling_attempts": attempts,
            "total_predicted_safe_in_attempts": total_ps,
            "predicted_safe_prior": predicted_safe_prior,
            "empty_predicted_safe": empty_predicted_safe,
        }
        prior_str = (
            f"{predicted_safe_prior:.4f}"
            if predicted_safe_prior is not None
            else "n/a"
        )
        print(
            f"Stratified sampling drew "
            f"{sample_info['n_predicted_safe']} predicted-safe and "
            f"{sample_info['n_predicted_unsafe']} predicted-unsafe states "
            f"in {attempts} attempts "
            f"(predicted-safe prior ≈ {prior_str})."
        )
        if empty_predicted_safe:
            print(
                "Predicted-safe set appears empty under the current model — "
                "skipping safe stratum and reporting NaN safe-stratum metrics."
            )
    elif sampling == "random":
        num_samples = val_cfg["num_samples"]
        states = dynamics.get_uniform_state_samples(
            num_samples=num_samples, requires_grad=False
        )
        sampling_meta = {"sampling": "random", "num_samples": int(num_samples)}
    elif sampling == "grid":
        grid_shape = list(val_cfg["grid_shape"])
        states = dynamics.get_uniform_state_grid(
            grid_shape=grid_shape, requires_grad=False
        ).reshape(-1, dynamics.nx)
        sampling_meta = {"sampling": "grid", "grid_shape": grid_shape}
    else:
        raise ValueError(
            f"Unknown validation.sampling: {sampling!r}. "
            "Expected 'stratified', 'random', or 'grid'."
        )

    save_trajectories = bool(val_cfg.get("save_trajectories", False))

    print(
        f"\nRunning validation on {states.shape[0]} initial states "
        f"(T={T}, dt={dt})..."
    )
    if device.type == "cuda":
        torch.cuda.synchronize(device)
    t_val_start = time.time()
    result = validate_cbf(
        dynamics=dynamics,
        states=states,
        constr_fn=constr_fn,
        residual_fn=model,
        T=T,
        dt=dt,
        return_values=True,
        return_initial_cbf=True,
        return_state_trajs=save_trajectories,
        return_control_trajs=save_trajectories,
        batch_size=val_cfg.get("batch_size"),
        predicted_safe_prior=predicted_safe_prior,
    )
    if device.type == "cuda":
        torch.cuda.synchronize(device)
    t_val = time.time() - t_val_start
    sm = result["stratified_metrics"]
    ps, pu = sm["predicted_safe"], sm["predicted_unsafe"]
    print("Validation per-stratum metrics:")
    print(
        f"  predicted_safe   : n={ps['n']:>7d}  "
        f"precision={ps['precision']:6.2f}%  "
        f"false_safe_rate={ps['false_safe_rate']:6.2f}%"
    )
    print(
        f"  predicted_unsafe : n={pu['n']:>7d}  "
        f"precision={pu['precision']:6.2f}%  "
        f"false_unsafe_rate={pu['false_unsafe_rate']:6.2f}%"
    )
    vm = result["volume_metrics"]
    print(
        f"  volume ratios    : predicted_safe={vm['predicted_safe_vol_ratio']:.4f}  "
        f"validated_safe={vm['validated_safe_vol_ratio']:.4f}  "
        f"(estimation={vm['estimation']})"
    )

    output_path = val_cfg.get("output_path") or os.path.join(
        default_dir, "validation.pt"
    )
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)

    metadata = {
        "system": dynamics.name,
        "T": float(T),
        "dt": float(dt),
        "n_steps": int(round(T / dt)),
        "n_states": int(states.shape[0]),
        **sampling_meta,
        "stratified_metrics": _jsonify_metrics(sm),
        "volume_metrics": _jsonify_volume_metrics(result["volume_metrics"]),
        "device": _describe_device(device),
        "validation_time_sec": float(t_val),
    }

    payload: dict = {
        "states": states.detach().cpu(),
        "values": result["values"].detach().cpu(),
        "initial_cbf": result["initial_cbf"].detach().cpu(),
        **metadata,
    }
    if save_trajectories:
        payload["state_traj"] = result["state_traj"].detach().cpu()
        payload["control_traj"] = result["control_traj"].detach().cpu()

    torch.save(payload, output_path)
    json_path = os.path.splitext(output_path)[0] + ".json"
    with open(json_path, "w") as f:
        json.dump(metadata, f, indent=2)

    print(f"Validation results saved to: {output_path}")
    print(f"Validation summary saved to: {json_path}")
    return t_val


def _jsonify_metrics(sm: dict) -> dict:
    """Convert numpy/torch scalars in the stratified-metrics dict to Python floats/ints."""
    out: dict = {}
    for stratum, sub in sm.items():
        out[stratum] = {
            k: (int(v) if k == "n" else float(v)) for k, v in sub.items()
        }
    return out


def _jsonify_volume_metrics(vm: dict) -> dict:
    """Convert numpy/torch scalars in the volume-metrics dict to JSON-friendly types."""
    return {
        "predicted_safe_vol_ratio": float(vm["predicted_safe_vol_ratio"]),
        "validated_safe_vol_ratio": float(vm["validated_safe_vol_ratio"]),
        "estimation": str(vm["estimation"]),
    }


def _describe_device(device: torch.device) -> dict:
    """Return a JSON-serializable description of the device used."""
    info: dict = {"type": device.type, "str": str(device)}
    if device.type == "cuda":
        idx = device.index if device.index is not None else torch.cuda.current_device()
        info["index"] = int(idx)
        info["name"] = torch.cuda.get_device_name(idx)
    return info


def main() -> None:
    parser = argparse.ArgumentParser(description="Train a VertexCBF value function.")
    parser.add_argument(
        "--config", required=True, help="Path to YAML experiment config."
    )
    parser.add_argument(
        "--resume",
        default=None,
        help="Path to a checkpoint .pt file to resume training from.",
    )
    parser.add_argument(
        "--validate-only",
        action="store_true",
        help=(
            "Skip data generation and training; run validation only. "
            "Loads --resume if given, otherwise defaults to <checkpoint_dir>/final.pt."
        ),
    )
    parser.add_argument(
        "--no-data",
        action="store_true",
        help="Disable data loss (PDE loss only), ignoring data.enabled in config.",
    )
    parser.add_argument(
        "--reuse-data",
        action="store_true",
        help=(
            "Reuse cached supervision data at data.cache_path if it exists. "
            "By default the cache is regenerated on every run."
        ),
    )
    parser.add_argument(
        "--device",
        default=None,
        help="Device string, e.g. 'cuda' or 'cpu'.  Auto-detected if omitted.",
    )
    args = parser.parse_args()

    with open(args.config) as f:
        cfg = yaml.safe_load(f)

    device_str = args.device or ("cuda" if torch.cuda.is_available() else "cpu")
    device = torch.device(device_str)
    print(f"Using device: {device}")
    print(f"Config: {args.config}")

    # Build components
    dynamics = build_dynamics(cfg["system"], device=device)
    constr_fn = build_constr_fn(cfg["constraint"])
    model = build_model(cfg["model"], dynamics, device=device)
    print(f"Model: {model}")

    out_cfg = cfg.get("output", {})
    group = method_group(cfg.get("data", {}), no_data_override=args.no_data)
    checkpoint_dir = out_cfg.get("checkpoint_dir") or f"checkpoints/{group}/{dynamics.name}"
    print(f"Method group: {group}")
    print(f"Checkpoint dir: {checkpoint_dir}")

    if args.validate_only:
        checkpoint = args.resume or os.path.join(checkpoint_dir, "final.pt")
        if not os.path.isfile(checkpoint):
            raise FileNotFoundError(
                f"--validate-only: checkpoint not found at '{checkpoint}'. "
                "Pass --resume to specify a different path."
            )
        print(f"Loading checkpoint: {checkpoint}")
        ckpt = torch.load(checkpoint, map_location=device, weights_only=True)
        model.load_state_dict(ckpt["model_state"])
        t_val = _run_validation(
            cfg, dynamics, constr_fn, model, default_dir=checkpoint_dir, device=device
        )
        return

    # Supervision data
    data_from_cache = False
    if args.no_data:
        data_states, data_values, t_data = None, None, None
    else:
        data_states, data_values, t_data = _get_data(
            cfg, dynamics, constr_fn, device, reuse_data=args.reuse_data
        )
        if data_states is not None and t_data is None:
            data_from_cache = True

    # When data was loaded from cache, recover the real generation time from the
    # previous timing.json so the summary reflects actual computation cost.
    if data_from_cache:
        timing_path = os.path.join(checkpoint_dir, "timing.json")
        if os.path.isfile(timing_path):
            with open(timing_path) as f:
                prev = json.load(f)
            t_data = prev.get("data_generation_time_sec")

    train_cfg = cfg.get("training", {})

    pde_cfg = cfg.get("pde", {})
    pde_sampling = pde_cfg.get("sampling", "grid")
    if pde_sampling == "random":
        pde_kwargs = {"pde_num_samples": pde_cfg["num_samples"], "pde_grid_shape": None}
    else:
        pde_kwargs = {"pde_grid_shape": tuple(pde_cfg.get("grid_shape", [100, 100]))}

    trainer = Trainer(
        dynamics=dynamics,
        model=model,
        constr_fn=constr_fn,
        epochs=train_cfg.get("epochs", 10000),
        lr=train_cfg.get("lr", 1e-3),
        lr_milestones=train_cfg.get("lr_milestones", []),
        lr_gamma=train_cfg.get("lr_gamma", 0.1),
        **pde_kwargs,
        pde_weight_mode=train_cfg.get("pde_weight_mode", "fixed"),
        pde_weight=train_cfg.get("pde_weight", 1.0),
        pde_weight_milestones=train_cfg.get("pde_weight_milestones", []),
        data_states=data_states,
        data_values=data_values,
        log_every=out_cfg.get("log_every", 20),
        checkpoint_dir=checkpoint_dir,
        checkpoint_every=out_cfg.get("checkpoint_every", 1000),
        resume_from=args.resume,
    )

    print(f"\nStarting training for {train_cfg.get('epochs', 10000)} epochs...")
    if device.type == "cuda":
        torch.cuda.synchronize(device)
    t_train_start = time.time()
    trainer.train()
    if device.type == "cuda":
        torch.cuda.synchronize(device)
    t_train = time.time() - t_train_start

    print("Training complete.")

    t_val = _run_validation(
        cfg, dynamics, constr_fn, model, default_dir=checkpoint_dir, device=device
    )

    t_total = (t_data or 0.0) + t_train + (t_val or 0.0)

    data_generation_skipped = bool(args.no_data) or not cfg.get("data", {}).get("enabled", True)
    print(f"\n--- Timing summary ---")
    if data_generation_skipped:
        print(f"  Data generation time : skipped")
    elif data_from_cache:
        t_data_str = f"{t_data:.3f}s (from previous run)" if t_data is not None else "unknown (loaded from cache)"
        print(f"  Data generation time : {t_data_str}")
    else:
        print(f"  Data generation time : {t_data:.3f}s")
    print(f"  Training time        : {t_train:.3f}s")
    if t_val is not None:
        print(f"  Validation time      : {t_val:.3f}s")
    print(f"  Total time           : {t_total:.3f}s")
    print(f"  Device               : {device}")

    timing_payload = {
        "device": _describe_device(device),
        "config": os.path.abspath(args.config),
        "system": dynamics.name,
        "data_generation_time_sec": None if t_data is None else float(t_data),
        "data_generation_skipped": data_generation_skipped,
        "data_loaded_from_cache": data_from_cache,
        "training_time_sec": float(t_train),
        "training_epochs": int(train_cfg.get("epochs", 10000)),
        "validation_time_sec": None if t_val is None else float(t_val),
        "total_time_sec": float(t_total),
    }
    timing_path = os.path.join(checkpoint_dir, "timing.json")
    os.makedirs(os.path.dirname(os.path.abspath(timing_path)), exist_ok=True)
    with open(timing_path, "w") as f:
        json.dump(timing_payload, f, indent=2)
    print(f"  Timing summary saved to: {timing_path}")


if __name__ == "__main__":
    main()
